### ISSUE TITLE
crash on windows 10 dll missing

### ISSUE THREAD

**Issue by bahmantorkian** [kwongtn/Bluecoins-ImportTool#3]
Cant get this to work. Keeps giving me dll missing. Even afer copying the required dlls, crashes on start. Any comments?

**Comment by kwongtn** [comment]
Hi, sorry for being this late on responding on your issue.
I'm a programming novice at the time of publishing of the project and as such I don't know how to respond & solve your issue 😅

For now, the crash should be fixed on the upcoming v2.0 release, where I package the required DLLs with the executable file in a zipped folder.

Very sorry for taking such a long time to fix such a trivial bug 😅
